version: '2' 
services: 
  zookeeper: 
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper 
    container_name: zookeeper 
    ports: 
      - "2181:2181" 
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181 
      ZOOKEEPER_TICK_TIME: 2000 
 
  broker: 
    image: confluentinc/cp-kafka:latest
    hostname: broker 
    container_name: broker 
    depends_on: 
      - zookeeper 
    ports: 
      - "9092:9092" 
    environment: 
      KAFKA_BROKER_ID: 1 
      KAFKA_BOOTSTRAP.SERVERS: 'broker:9092' 
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181' 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT 
      KAFKA_LISTENERS: PLAINTEXT://:9092 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.1.7.41:9092 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0 
 
  control-center: 
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center 
    container_name: control-center 
    depends_on: 
      - zookeeper 
      - broker 
    ports: 
      - "9021:9021" 
    environment: 
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:9092' 
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181' 
      CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083' 
      CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088" 
      CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://10.1.7.41:8088" 
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081" 
      CONTROL_CENTER_REPLICATION_FACTOR: 1 
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1 
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1 
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1 
      PORT: 9021